"""
Django settings for ZOOT project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Chargé depuis .env — ne jamais mettre la clé en dur dans ce fichier
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
DJANGO_DEBUG=True

# ── Email ─────────────────────────────────────────────────────────────────────
# En développement : affiche les e-mails dans la console (pas d'envoi réel)
# En production   : Brevo via HTTP API (django-anymail) — Railway bloque le SMTP sortant
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND  = 'anymail.backends.brevo.EmailBackend'
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@vazimba.io')
    ANYMAIL = {
        'BREVO_API_KEY': config('BREVO_API_KEY', default=''),
    }

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,www.vazimba.io,vazimba.io', cast=Csv())

# Railway health check — toujours autoriser le domaine de health check de Railway
# (évite les boucles de redémarrage causées par les 400 sur le health check)
if not DEBUG:
    _railway_hosts = ['.railway.app', 'healthcheck.railway.app', 'www.vazimba.io', 'vazimba.io']
    for _h in _railway_hosts:
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)

AUTH_USER_MODEL = 'account.Account'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'account.backends.CaseInsensitiveModelBackend',
)

# Application definition

INSTALLED_APPS = [
    # ── Daphne doit être PREMIER dans INSTALLED_APPS ──────────────────────────
    # Obligatoire pour que `python manage.py runserver` utilise Daphne (ASGI)
    # au lieu du serveur WSGI intégré à Django. Doit précéder 'channels'.
    # FIX : était après 'channels' — ordre incorrect.
    'daphne',

    # ── WhiteNoise — désactive le serveur de fichiers statiques de Django ──────
    # (doit être AVANT django.contrib.staticfiles)
    'whitenoise.runserver_nostatic',

    # ── Applications du projet ─────────────────────────────────────────────────
    'account',
    'personal',
    'legal',
    'friend',
    'public_chat',
    'stories',
    'channels',
    'django.contrib.humanize',
    'chat',
    'notification',
    'post',
    'group',
    'video',
    'bazar',
    'pwa',
    'ckeditor',
    'crispy_forms',
    # FIX : django-crispy-forms 2.x a extrait les template packs en packages séparés.
    # 'bootstrap3' n'est plus inclus par défaut. On utilise bootstrap4 (voir CRISPY_TEMPLATE_PACK).
    'crispy_bootstrap4',

    # ── Django core ────────────────────────────────────────────────────────────
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # ── Utilitaires ────────────────────────────────────────────────────────────
    # FIX : présent dans requirements.txt mais absent de INSTALLED_APPS.
    'django_extensions',      # Commandes pratiques : shell_plus, graph_models, etc.

    # ── Email transactionnel (HTTP API via Brevo) ───────────────────────────────
    'anymail',
]
# NOTE : 'redis' a été SUPPRIMÉ de INSTALLED_APPS — c'est un client Python
# (bibliothèque), pas une application Django. L'inclure ici est une erreur.

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise — servir les fichiers statiques en production (juste après SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # LocaleMiddleware DOIT être après SessionMiddleware et avant CommonMiddleware
    # Il lit la langue depuis : cookie → session → Accept-Language header
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ZOOT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'ZOOT.wsgi.application'
ASGI_APPLICATION = "ZOOT.routing.application"

# Channel layer : Redis si REDIS_URL est explicitement défini (plugin Railway),
# sinon InMemoryChannelLayer (fonctionne pour 1 worker — Railway Starter/free tier).
_redis_url = config('REDIS_URL', default='')
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {"hosts": [_redis_url]},
        },
    }
else:
    # Pas de Redis configuré → channel layer en mémoire (WS fonctionne, push cross-worker non)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Les identifiants sont chargés depuis le fichier .env (jamais en dur ici)

# ── Base de données ───────────────────────────────────────────────────────────
# Si DATABASE_URL est définie (Railway / Heroku), elle a la priorité.
# Sinon, les variables individuelles du .env local sont utilisées.
_DATABASE_URL = config('DATABASE_URL', default=None)
_DB_PASSWORD  = config('DB_PASSWORD', default=None)

if _DATABASE_URL:
    # Production (Railway, Heroku, etc.) — URL complète
    _db_config = dj_database_url.parse(
        _DATABASE_URL,
        conn_max_age=600,
        ssl_require=False,
    )
    _db_config['CONN_HEALTH_CHECKS'] = True   # Django 4.1+ — évite les connexions stales
    DATABASES = {'default': _db_config}
elif _DB_PASSWORD:
    # Dev avec PostgreSQL local — credentials définis dans .env
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': config('DB_NAME', default='social_db'),
            'USER': config('DB_USER', default='social_user'),
            'PASSWORD': _DB_PASSWORD,
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    # Dev sans PostgreSQL — SQLite (aucune config requise)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ── Internationalisation ──────────────────────────────────────────────────────
# Docs : https://docs.djangoproject.com/en/4.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'fr'   # Langue par défaut : français

LANGUAGES = [
    ('fr', _('Français')),
    ('en', _('English')),
    ('mg', _('Malagasy')),
]

# Chemin vers les fichiers de traduction du projet
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Nom du cookie de langue (lu par LocaleMiddleware)
LANGUAGE_COOKIE_NAME = 'zoot_language'
LANGUAGE_COOKIE_AGE  = 365 * 24 * 3600   # 1 an

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')

# ── Médias (fichiers uploadés) — Cloudflare R2 ──────────────────────────────
# R2 = stockage S3-compatible sans frais de bande passante (10 Go gratuit/mois)
# Variables d'environnement à définir dans Railway :
#   R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_ACCOUNT_ID,
#   R2_BUCKET_NAME, R2_PUBLIC_URL (ex: pub-xxx.r2.dev ou media.ton-domaine.com)

R2_ACCOUNT_ID        = config('R2_ACCOUNT_ID', default=None)
# Support both R2_ACCESS_KEY_ID and R2_ACCESS_KEY (Railway variable name)
R2_ACCESS_KEY_ID     = config('R2_ACCESS_KEY_ID', default=None) or config('R2_ACCESS_KEY', default=None)
R2_SECRET_ACCESS_KEY = config('R2_SECRET_ACCESS_KEY', default=None)
R2_BUCKET_NAME       = config('R2_BUCKET_NAME', default='vazimba-media')
# Support both R2_PUBLIC_URL and CLOUDFLARE_R2_PUBLIC_URL
_r2_pub_raw = config('R2_PUBLIC_URL', default=None) or config('CLOUDFLARE_R2_PUBLIC_URL', default=None)
# Strip https:// prefix if present (we add it ourselves)
R2_PUBLIC_URL = _r2_pub_raw.replace('https://', '').replace('http://', '').rstrip('/') if _r2_pub_raw else None

if R2_ACCOUNT_ID and R2_ACCESS_KEY_ID and R2_SECRET_ACCESS_KEY:
    # ── Production : Cloudflare R2 ──────────────────────────────────────────
    AWS_ACCESS_KEY_ID     = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    # Support R2_ENDPOINT variable or build from account ID
    _r2_endpoint = config('R2_ENDPOINT', default=None)
    AWS_S3_ENDPOINT_URL   = _r2_endpoint or f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    AWS_S3_REGION_NAME    = 'auto'
    AWS_DEFAULT_ACL       = 'public-read'
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_QUERYSTRING_AUTH  = False   # URLs publiques sans signature

    # URL publique des médias servis par R2 (CDN ou r2.dev)
    if R2_PUBLIC_URL:
        AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_URL
        MEDIA_URL = f"https://{R2_PUBLIC_URL}/"
    else:
        MEDIA_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com/{R2_BUCKET_NAME}/"

    _media_backend = 'ZOOT.storage.R2MediaStorage'
else:
    # ── Développement : stockage local ──────────────────────────────────────
    MEDIA_URL  = '/media/'
    _media_backend = 'django.core.files.storage.FileSystemStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')

# ── Stockage (Django 4.2+) ────────────────────────────────────────────────────
STORAGES = {
    "default": {
        "BACKEND": _media_backend,
    },
    "staticfiles": {
        # WhiteNoise avec fallback sur les fichiers absents du manifeste (CKEditor, etc.)
        "BACKEND": "ZOOT.storage.RelaxedStaticFilesStorage",
    },
}

TEMP = os.path.join(BASE_DIR, 'media_cdn/temp')

# Taille max des données POST non-fichier (formulaires, crop base64, etc.)
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024   # 100 Mo

# Taille max d'un fichier maintenu en mémoire avant d'être streamé sur disque.
# Au-delà de cette valeur, Django écrit dans un fichier temporaire.
# (N'est PAS une limite dure sur la taille du fichier uploadé.)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024    # 10 Mo (seuil mémoire↔disque)

# FIX : 'bootstrap3' n'est plus inclus dans django-crispy-forms 2.x.
# On utilise 'bootstrap4' via le package crispy-bootstrap4 (voir INSTALLED_APPS + requirements.txt).
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# URL de base de l'application (utilisée dans les e-mails, liens de partage, etc.)
BASE_URL = config('BASE_URL', default='https://www.vazimba.io')

# ── Web Push Notifications (VAPID) ───────────────────────────────────────────
VAPID_PUBLIC_KEY   = config('VAPID_PUBLIC_KEY',   default='')
VAPID_PRIVATE_KEY  = config('VAPID_PRIVATE_KEY',  default='')
VAPID_CLAIMS_EMAIL = config('VAPID_CLAIMS_EMAIL', default='admin@vazimba.com')

# ── SMS (vérification numéro de téléphone) ────────────────────────────────────
# Fournisseur : Africa's Talking (meilleur rapport qualité/prix pour Madagascar)
# En développement : backend console (aucun SMS réel envoyé)
# En production    : backend Africa's Talking
# Variables Railway à créer :
#   AT_USERNAME  → username Africa's Talking (ex: "vazimba")
#   AT_API_KEY   → clé API Africa's Talking
#   AT_SENDER    → ID expéditeur (ex: "VAZIMBA", optionnel selon opérateur)
SMS_BACKEND  = config('SMS_BACKEND', default='console' if DEBUG else 'africastalking')
AT_USERNAME  = config('AT_USERNAME', default='sandbox')
AT_API_KEY   = config('AT_API_KEY',  default='atsk_sandbox_key')
AT_SENDER    = config('AT_SENDER',   default='VAZIMBA')
# Durée de validité du code OTP (minutes)
SMS_OTP_VALID_MINUTES = 10
# Max envois par numéro par heure (anti-abus)
SMS_OTP_MAX_SENDS_PER_HOUR = 3

# ── Recherche musique (Jamendo — gratuit, libre de droits) ────────────────────
# Créer un compte gratuit sur https://developer.jamendo.com/ pour obtenir un client_id
# La valeur par défaut est l'ID de démo Jamendo (fonctionnel, mais limité)
JAMENDO_CLIENT_ID = config('JAMENDO_CLIENT_ID', default='b6747d04')

# ── Cache (pour les trending hashtags) ───────────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'zoot-cache',
    }
}

# ── Sécurité production ───────────────────────────────────────────────────────
# Domaines autorisés pour les requêtes CSRF (obligatoire pour Railway / HTTPS)
import re as _re

def _clean_csrf_origins(raw_list):
    """
    Nettoie les valeurs CSRF_TRUSTED_ORIGINS :
    - Supprime les liens markdown [texte](url) → garde juste l'URL
    - Ajoute https:// si le schéma est absent
    - Ignore les valeurs vides
    """
    cleaned = []
    for origin in raw_list:
        origin = origin.strip()
        if not origin:
            continue
        # Extraire l'URL d'un lien markdown [texte](url)
        md = _re.match(r'\[.*?\]\((https?://[^)]+)\)', origin)
        if md:
            origin = md.group(1)
        # Ajouter https:// si manquant
        if not origin.startswith(('http://', 'https://')):
            origin = 'https://' + origin
        cleaned.append(origin)
    return cleaned

CSRF_TRUSTED_ORIGINS = _clean_csrf_origins(config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1:8000,http://localhost:8000',
    cast=Csv()
))

# Ajoute automatiquement les domaines Railway + domaine custom si non déjà présents
if not DEBUG:
    _auto_csrf = [
        'https://*.railway.app',
        'https://*.up.railway.app',
        'https://vazimba.io',
        'https://www.vazimba.io',
    ]
    for _origin in _auto_csrf:
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

# En production (DEBUG=False), activer les redirections HTTPS
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True