"""
Django settings for ZOOT project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Chargé depuis .env — ne jamais mettre la clé en dur dans ce fichier
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ── Email ─────────────────────────────────────────────────────────────────────
# En développement : affiche les e-mails dans la console (pas d'envoi réel)
# En production   : serveur SMTP configuré via variables d'environnement
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND       = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST          = config('EMAIL_HOST',     default='smtp.gmail.com')
    EMAIL_PORT          = config('EMAIL_PORT',     default=587, cast=int)
    EMAIL_USE_TLS       = config('EMAIL_USE_TLS',  default=True, cast=bool)
    EMAIL_HOST_USER     = config('EMAIL_HOST_USER',     default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL',  default=config('EMAIL_HOST_USER', default=''))

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

# Railway health check — toujours autoriser le domaine de health check de Railway
# (évite les boucles de redémarrage causées par les 400 sur le health check)
if not DEBUG:
    _railway_hosts = ['.railway.app', 'healthcheck.railway.app']
    for _h in _railway_hosts:
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)

AUTH_USER_MODEL = 'account.Account'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'account.backends.CaseInsensitiveModelBackend',
)

# Application definition

INSTALLED_APPS = [
    # ── Daphne doit être PREMIER dans INSTALLED_APPS ──────────────────────────
    # Obligatoire pour que `python manage.py runserver` utilise Daphne (ASGI)
    # au lieu du serveur WSGI intégré à Django. Doit précéder 'channels'.
    # FIX : était après 'channels' — ordre incorrect.
    'daphne',

    # ── Jazzmin — personnalise l'interface admin ───────────────────────────────
    # Doit être avant 'django.contrib.admin' pour surcharger les templates admin.
    # FIX : présent dans requirements.txt mais absent de INSTALLED_APPS.
    'jazzmin',

    # ── WhiteNoise — désactive le serveur de fichiers statiques de Django ──────
    # (doit être AVANT django.contrib.staticfiles)
    'whitenoise.runserver_nostatic',

    # ── Applications du projet ─────────────────────────────────────────────────
    'account',
    'personal',
    'friend',
    'public_chat',
    'channels',
    'django.contrib.humanize',
    'chat',
    'notification',
    'post',
    'ckeditor',
    'crispy_forms',
    # FIX : django-crispy-forms 2.x a extrait les template packs en packages séparés.
    # 'bootstrap3' n'est plus inclus par défaut. On utilise bootstrap4 (voir CRISPY_TEMPLATE_PACK).
    'crispy_bootstrap4',

    # ── Stockage cloud médias — doit être AVANT django.contrib.staticfiles ─────
    'cloudinary_storage',
    'cloudinary',

    # ── Django core ────────────────────────────────────────────────────────────
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # ── Utilitaires ────────────────────────────────────────────────────────────
    # FIX : présent dans requirements.txt mais absent de INSTALLED_APPS.
    'django_extensions',      # Commandes pratiques : shell_plus, graph_models, etc.
]
# NOTE : 'redis' a été SUPPRIMÉ de INSTALLED_APPS — c'est un client Python
# (bibliothèque), pas une application Django. L'inclure ici est une erreur.

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise — servir les fichiers statiques en production (juste après SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ZOOT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ZOOT.wsgi.application'
ASGI_APPLICATION = "ZOOT.routing.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # En production (Railway) : REDIS_URL est fourni par le plugin Redis de Railway
            # En local : utilise redis://127.0.0.1:6379 par défaut
            "hosts": [config('REDIS_URL', default='redis://127.0.0.1:6379')],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Les identifiants sont chargés depuis le fichier .env (jamais en dur ici)

# ── Base de données ───────────────────────────────────────────────────────────
# Si DATABASE_URL est définie (Railway / Heroku), elle a la priorité.
# Sinon, les variables individuelles du .env local sont utilisées.
_DATABASE_URL = config('DATABASE_URL', default=None)

if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,   # Railway gère le SSL en interne ; passer à True si besoin
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': config('DB_NAME', default='social_db'),
            'USER': config('DB_USER', default='social_user'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')

# ── Médias (fichiers uploadés) ────────────────────────────────────────────────
# En production : Cloudinary (fichiers persistants entre déploiements Railway)
# En développement : stockage local
CLOUDINARY_URL = config('CLOUDINARY_URL', default=None)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')

if CLOUDINARY_URL:
    import cloudinary
    cloudinary.config(cloudinary_url=CLOUDINARY_URL)
    CLOUDINARY_STORAGE = {'CLOUDINARY_URL': CLOUDINARY_URL}
    _media_backend = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    _media_backend = 'django.core.files.storage.FileSystemStorage'

# ── Stockage (Django 4.2+) ────────────────────────────────────────────────────
# FIX : STATICFILES_STORAGE et DEFAULT_FILE_STORAGE sont dépréciés en Django 4.2.
# On utilise le nouveau dictionnaire STORAGES à la place.
STORAGES = {
    "default": {
        "BACKEND": _media_backend,
    },
    "staticfiles": {
        # WhiteNoise avec fallback sur les fichiers absents du manifeste (CKEditor, etc.)
        "BACKEND": "ZOOT.storage.RelaxedStaticFilesStorage",
    },
}

TEMP = os.path.join(BASE_DIR, 'media_cdn/temp')

# Taille max des données POST non-fichier (formulaires, crop base64, etc.)
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024   # 100 Mo

# Taille max d'un fichier maintenu en mémoire avant d'être streamé sur disque.
# Au-delà de cette valeur, Django écrit dans un fichier temporaire.
# (N'est PAS une limite dure sur la taille du fichier uploadé.)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024    # 10 Mo (seuil mémoire↔disque)

# FIX : 'bootstrap3' n'est plus inclus dans django-crispy-forms 2.x.
# On utilise 'bootstrap4' via le package crispy-bootstrap4 (voir INSTALLED_APPS + requirements.txt).
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# URL de base de l'application (utilisée dans les e-mails, liens de partage, etc.)
BASE_URL = config('BASE_URL', default='http://127.0.0.1:8000')

# ── Sécurité production ───────────────────────────────────────────────────────
# Domaines autorisés pour les requêtes CSRF (obligatoire pour Railway / HTTPS)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1:8000,http://localhost:8000',
    cast=Csv()
)
# Ajoute automatiquement les domaines Railway si non déjà présents
if not DEBUG:
    _railway_csrf = ['https://*.railway.app', 'https://*.up.railway.app']
    for _origin in _railway_csrf:
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

# En production (DEBUG=False), activer les redirections HTTPS
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True

#cdn = constants directory network

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
