"""
Django settings for ZOOT project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Chargé depuis .env — ne jamais mettre la clé en dur dans ce fichier
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Développement seulement

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost, .railway.app', cast=Csv())

# Railway health check — toujours autoriser le domaine de health check de Railway
# (évite les boucles de redémarrage causées par les 400 sur le health check)
if not DEBUG:
    _railway_hosts = ['.railway.app', 'healthcheck.railway.app']
    for _h in _railway_hosts:
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)

AUTH_USER_MODEL = 'account.Account'

AUTHENTICATION_BACKENDS = ( 
    'django.contrib.auth.backends.AllowAllUsersModelBackend', 
    'account.backends.CaseInsensitiveModelBackend',
    )

# Application definition

INSTALLED_APPS = [
    # WhiteNoise — désactive le serveur de fichiers statiques de Django en développement
    # (doit être AVANT django.contrib.staticfiles)
    'whitenoise.runserver_nostatic',

    'account',
    'personal',
    'friend',
    'public_chat',
    'channels', # or daphne
    'daphne',
    'redis',
    'django.contrib.humanize',
    'chat',
    'notification',
    'post',
    'ckeditor',
    'crispy_forms',





    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise — servir les fichiers statiques en production (juste après SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ZOOT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ZOOT.wsgi.application'
ASGI_APPLICATION = "ZOOT.routing.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # En production (Railway) : REDIS_URL est fourni par le plugin Redis de Railway
            # En local : utilise redis://127.0.0.1:6379 par défaut
            "hosts": [config('REDIS_URL', default='redis://127.0.0.1:6379')],
        },
    },
}



# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Les identifiants sont chargés depuis le fichier .env (jamais en dur ici)

# ── Base de données ───────────────────────────────────────────────────────────
# Si DATABASE_URL est définie (Railway / Heroku), elle a la priorité.
# Sinon, les variables individuelles du .env local sont utilisées.
_DATABASE_URL = config('DATABASE_URL', default=None)

if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,   # Railway gère le SSL en interne ; passer à True si besoin
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': config('DB_NAME', default='social_db'),
            'USER': config('DB_USER', default='social_user'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # Note : 'media/' retiré des STATICFILES_DIRS — les fichiers uploadés
    # ne doivent pas être collectés comme fichiers statiques.
]
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')

TEMP = os.path.join(BASE_DIR, 'media_cdn/temp')

# WhiteNoise — compression + cache-busting des fichiers statiques
# Utilise notre sous-classe permissive (manifest_strict=False) pour éviter
# les erreurs sur les sourcemaps .map ou autres fichiers référencés mais absents.
STATICFILES_STORAGE = 'ZOOT.storage.RelaxedStaticFilesStorage'

CRISPY_TEMPLATE_PACK = 'bootstrap3'

# URL de base de l'application (utilisée dans les e-mails, liens de partage, etc.)
BASE_URL = config('BASE_URL', default='http://127.0.0.1:8000')

# ── Sécurité production ───────────────────────────────────────────────────────
# Domaines autorisés pour les requêtes CSRF (obligatoire pour Railway / HTTPS)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1:8000,http://localhost:8000',
    cast=Csv()
)

# En production (DEBUG=False), activer les redirections HTTPS
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True

#cdn = constants directory network

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'