# Generated by Django 4.2.25 on 2026-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_phone_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(help_text='Format E.164 (+261XXXXXXXXX)', max_length=20, verbose_name='Numéro en cours de vérification'),
        ),
    ]
