# Generated by Django 5.2.7 on 2026-10-07 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_groupjoinrequest'),
        ('post', '0020_post_lieu'),
        ('tourisme', '0002_lieuavis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='comment_post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-id'], name='post_author_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['region', '-id'], name='post_region_recent_idx'),
        ),
    ]
