# Generated by Django 5.2.7 on 2026-10-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_comment_comment_post_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='post_media/posters/'),
        ),
    ]
