# Generated by Django 5.2.7 on 2026-10-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0009_annonce_location_fields'),
        ('post', '0022_postmedia_poster'),
        ('resto', '0006_composed_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='annonce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='bazar.annonce', verbose_name='Annonce Bazar liée'),
        ),
        migrations.AddField(
            model_name='post',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='resto.menuitem', verbose_name='Plat Resto lié'),
        ),
    ]
