# Generated by Django 4.2 on 2023-06-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(help_text='users who are connected to chat room.', related_name='Chat_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicroomchatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chat_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
