# Generated by Django 5.2.7 on 2026-10-07 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messagereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='roomchatmessage',
            index=models.Index(fields=['room', 'timestamp'], name='chatmsg_room_time_idx'),
        ),
    ]
