# Generated by Django 4.2.25 on 2026-08-29 18:17

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_storyreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=stories.models.story_audio_path),
        ),
    ]
