from ZOOT.ratelimit import ratelimit
from .video_feed import video_feed_view, video_feed_more
from django.urls import path

from .views import (
    Index,
    AddPostView,
    post_feed_view,
    post_feed_more,
    UpdatePostView,
    DeletePostView,
    like_post,
    react_post,
    hashtag_view,
    tendances_view,
    mention_autocomplete,
    follow,
    unfollow,
    add_comment,
    new_comments,
    delete_comment,
    post_detail,
    repost_post,
    kabary_create,
    vintana_create,
    report_content,
    bookmark_post,
    mes_brouillons,
    mes_favoris_posts,
    diag_media,
    reactions_who,
)

app_name = 'post'

urlpatterns = [
    path('index/',        Index,                    name='index'),
    path('',              post_feed_view,           name='post-view'),
    path('add-post/',     ratelimit('10/m')(AddPostView.as_view()), name='addPost'),
    path('edit-post/<int:pk>/',   UpdatePostView.as_view(), name='edit-post'),
    path('delete-post/<int:pk>/', DeletePostView.as_view(), name='delete-post'),
    path('like/',         ratelimit('60/m')(like_post), name='like-post'),
    path('follow/',       follow,                   name='follow'),
    path('unfollow/',     unfollow,                 name='unfollow'),
    path('comment/<int:post_id>/add/',       ratelimit('15/m')(add_comment), name='add-comment'),
    path('comment/<int:post_id>/new/',       new_comments,   name='new-comments'),
    path('comment/<int:comment_id>/delete/', delete_comment, name='delete-comment'),
    path('feed/more/',         post_feed_more,        name='feed-more'),
    path('react/',             ratelimit('60/m')(react_post), name='react-post'),
    path('hashtag/<slug:tag>/', hashtag_view,         name='hashtag'),
    path('mention/autocomplete/', mention_autocomplete, name='mention-autocomplete'),
    path('bookmark/',          bookmark_post,         name='bookmark'),
    path('brouillons/',        mes_brouillons,        name='mes-brouillons'),
    path('sauvegardes/',       mes_favoris_posts,     name='mes-favoris-posts'),
    path('repost/',            ratelimit('20/m')(repost_post), name='repost'),
    path('kabary/create/',     ratelimit('10/m')(kabary_create), name='kabary-create'),
    path('vintana/create/',    ratelimit('10/m')(vintana_create), name='vintana-create'),
    path('tendances/',         tendances_view,        name='tendances'),
    path('videos/',            video_feed_view,       name='video-feed'),
    path('videos/more/',       video_feed_more,       name='video-feed-more'),
    path('signaler/',          ratelimit('10/h')(report_content), name='report-content'),
    path('diag/',              diag_media,            name='diag-media'),
    path('<int:post_id>/reactions/', reactions_who,  name='reactions-who'),
    path('<int:post_id>/',           post_detail,    name='post-detail'),
]
