# Generated by Django 4.2.25 on 2026-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_publicchatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosettings',
            name='gradient_to',
            field=models.CharField(default='#6c2bd9', help_text='Code couleur hexadécimal, ex. #6c2bd9', max_length=20, verbose_name='Couleur de fin (dégradé)'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='subtitle',
            field=models.TextField(default="Si vous connaissez ce que c'est Vazimba et que vous en êtes un(e), alors vous êtes au bon endroit car cette plateforme est conçue pour les Vazimba. Pour un partage d'idées, de messages et d'informations en temps réel.", verbose_name="Texte d'accroche"),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='title',
            field=models.CharField(default='Connectez-vous.\nPartagez. Grandissez.', help_text='Saut de ligne possible avec \\n — il sera affiché comme <br> dans le navigateur.', max_length=200, verbose_name='Titre principal (H1)'),
        ),
    ]
