# Generated by Django 4.2.25 on 2026-08-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_herosettings_gradient_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosettings',
            name='gradient_from',
            field=models.CharField(default='#5c2a08', help_text='Code couleur hexadécimal, ex. #5c2a08', max_length=20, verbose_name='Couleur de début (dégradé)'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='gradient_to',
            field=models.CharField(default='#A0522D', help_text='Code couleur hexadécimal, ex. #A0522D', max_length=20, verbose_name='Couleur de fin (dégradé)'),
        ),
    ]
