# Generated by Django 4.2.25 on 2026-08-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_hero_gradient_acajou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosettings',
            name='subtitle',
            field=models.TextField(default="Un fil d'actualité, une place de marché et un guide du pays — au même endroit.", help_text='Une phrase, affichée sous le titre. Les phrases courtes rendent mieux.', verbose_name="Texte d'accroche"),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='title',
            field=models.CharField(default='Le réseau social qui parle *malagasy*.', help_text="Saut de ligne possible avec \\n. Un mot entre *astérisques* s'affiche dans le serif italique de la charte — par exemple : Le réseau social qui parle *malagasy*.", max_length=200, verbose_name='Titre principal (H1)'),
        ),
    ]
