# Generated by Django 4.2.25 on 2026-09-05 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('vehicle', models.CharField(choices=[('moto', 'Moto / Scooter'), ('velo', 'Vélo'), ('voiture', 'Voiture'), ('pied', 'À pied')], default='moto', max_length=10, verbose_name='Véhicule')),
                ('region', models.CharField(blank=True, choices=[('', 'Toute Madagascar'), ('analamanga', 'Analamanga · Antananarivo'), ('vakinankaratra', 'Vakinankaratra · Antsirabe'), ('itasy', 'Itasy · Miarinarivo'), ('bongolava', 'Bongolava · Tsiroanomandidy'), ('haute_matsiatra', 'Haute Matsiatra · Fianarantsoa'), ('amoron_i_mania', "Amoron'i Mania · Ambositra"), ('vatovavy', 'Vatovavy · Mananjary'), ('fitovinany', 'Fitovinany · Manakara'), ('ihorombe', 'Ihorombe · Ihosy'), ('atsimo_atsinanana', 'Atsimo-Atsinanana · Farafangana'), ('atsinanana', 'Atsinanana · Toamasina'), ('analanjirofo', 'Analanjirofo · Fenoarivo Atsinanana'), ('alaotra_mangoro', 'Alaotra-Mangoro · Ambatondrazaka'), ('boeny', 'Boeny · Mahajanga'), ('sofia', 'Sofia · Antsohihy'), ('betsiboka', 'Betsiboka · Maevatanana'), ('melaky', 'Melaky · Maintirano'), ('atsimo_andrefana', 'Atsimo-Andrefana · Toliara'), ('androy', 'Androy · Ambovombe'), ('anosy', 'Anosy · Tolagnaro'), ('menabe', 'Menabe · Morondava'), ('diana', 'Diana · Antsiranana'), ('sava', 'Sava · Sambava'), ('diaspora', '🌍 Diaspora malgache')], db_index=True, default='', max_length=30, verbose_name='Région')),
                ('is_available', models.BooleanField(db_index=True, default=False, verbose_name='Disponible')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Approuvé')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('position_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom de la rubrique')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Rubrique de menu',
                'verbose_name_plural': 'Rubriques de menu',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du plat')),
                ('description', models.TextField(blank=True, default='', help_text='Ingrédients, portion, accompagnement…', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (Ar)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resto/items/%Y/%m/', verbose_name='Photo')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Disponible')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='resto.menucategory', verbose_name='Rubrique')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=12, unique=True, verbose_name='N° de commande')),
                ('status', models.CharField(choices=[('pending', 'En attente du restaurant'), ('accepted', 'Acceptée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('picked_up', 'Récupérée par le livreur'), ('delivering', 'En cours de livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refused', 'Refusée')], db_index=True, default='pending', max_length=12, verbose_name='Statut')),
                ('mode', models.CharField(choices=[('delivery', 'Livraison'), ('pickup', 'Retrait sur place')], default='delivery', max_length=10, verbose_name='Mode')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces à la livraison'), ('mvola', 'MVola'), ('orange', 'Orange Money'), ('airtel', 'Airtel Money')], default='cash', max_length=10, verbose_name='Paiement')),
                ('customer_name', models.CharField(max_length=80, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Téléphone du client')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=250, verbose_name='Adresse de livraison')),
                ('delivery_latitude', models.FloatField(blank=True, null=True)),
                ('delivery_longitude', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', verbose_name='Message au restaurant')),
                ('pickup_address', models.CharField(blank=True, default='', max_length=250)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Délai annoncé (min)')),
                ('refusal_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Motif')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='resto.courier', verbose_name='Livreur')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='resto.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resto.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast-food & Snack'), ('gargote', 'Gargote & Hotely'), ('patisserie', 'Pâtisserie & Boulangerie'), ('boissons', 'Boissons & Jus'), ('traiteur', 'Traiteur & Plats maison'), ('epicerie', 'Épicerie & Courses'), ('autre', 'Autre')], db_index=True, default='restaurant', max_length=20, verbose_name='Catégorie')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='resto/logos/%Y/%m/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='resto/banners/%Y/%m/', verbose_name='Bannière')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone / WhatsApp')),
                ('address', models.CharField(help_text='Quartier, rue, repère (ex: Analakely, en face de la pharmacie)', max_length=250, verbose_name='Adresse')),
                ('region', models.CharField(blank=True, choices=[('', 'Toute Madagascar'), ('analamanga', 'Analamanga · Antananarivo'), ('vakinankaratra', 'Vakinankaratra · Antsirabe'), ('itasy', 'Itasy · Miarinarivo'), ('bongolava', 'Bongolava · Tsiroanomandidy'), ('haute_matsiatra', 'Haute Matsiatra · Fianarantsoa'), ('amoron_i_mania', "Amoron'i Mania · Ambositra"), ('vatovavy', 'Vatovavy · Mananjary'), ('fitovinany', 'Fitovinany · Manakara'), ('ihorombe', 'Ihorombe · Ihosy'), ('atsimo_atsinanana', 'Atsimo-Atsinanana · Farafangana'), ('atsinanana', 'Atsinanana · Toamasina'), ('analanjirofo', 'Analanjirofo · Fenoarivo Atsinanana'), ('alaotra_mangoro', 'Alaotra-Mangoro · Ambatondrazaka'), ('boeny', 'Boeny · Mahajanga'), ('sofia', 'Sofia · Antsohihy'), ('betsiboka', 'Betsiboka · Maevatanana'), ('melaky', 'Melaky · Maintirano'), ('atsimo_andrefana', 'Atsimo-Andrefana · Toliara'), ('androy', 'Androy · Ambovombe'), ('anosy', 'Anosy · Tolagnaro'), ('menabe', 'Menabe · Morondava'), ('diana', 'Diana · Antsiranana'), ('sava', 'Sava · Sambava'), ('diaspora', '🌍 Diaspora malgache')], db_index=True, default='', max_length=30, verbose_name='Région')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('opening_hours', models.CharField(blank=True, default='', help_text='Ex : Lun–Sam 10h–22h', max_length=250, verbose_name='Horaires')),
                ('is_open', models.BooleanField(db_index=True, default=True, help_text='Décochez pour suspendre temporairement les commandes.', verbose_name='Ouvert (accepte les commandes)')),
                ('offers_delivery', models.BooleanField(default=True, verbose_name='Propose la livraison')),
                ('offers_pickup', models.BooleanField(default=True, verbose_name='Propose le retrait sur place')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Frais de livraison (Ar)')),
                ('min_order', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Commande minimum (Ar)')),
                ('avg_prep_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Temps de préparation moyen (min)')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Approuvé par Vazimba')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='resto.orderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente du restaurant'), ('accepted', 'Acceptée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('picked_up', 'Récupérée par le livreur'), ('delivering', 'En cours de livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refused', 'Refusée')], max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='resto.order')),
            ],
            options={
                'verbose_name': 'Événement de commande',
                'verbose_name_plural': 'Événements de commande',
                'ordering': ['at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='resto.restaurant', verbose_name='Restaurant'),
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex : Sauce, Cuisson, Suppléments, Boisson', max_length=100, verbose_name='Titre du groupe')),
                ('min_select', models.PositiveSmallIntegerField(default=0, help_text='0 = facultatif, 1 = au moins un choix obligatoire', verbose_name='Choix minimum')),
                ('max_select', models.PositiveSmallIntegerField(default=1, help_text='1 = un seul choix (boutons ronds), >1 = plusieurs cases à cocher, 0 = illimité', verbose_name='Choix maximum')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='resto.menuitem', verbose_name='Plat')),
            ],
            options={
                'verbose_name': "Groupe d'options",
                'verbose_name_plural': "Groupes d'options",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('extra_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Supplément (Ar)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='resto.optiongroup', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resto.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='resto.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='courier',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Vide = livreur indépendant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='resto.restaurant', verbose_name='Restaurant de rattachement'),
        ),
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', help_text='Ex : sans oignons, bien cuit', max_length=200, verbose_name='Instructions')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='resto.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_lines', to='resto.menuitem')),
                ('options', models.ManyToManyField(blank=True, related_name='cart_lines', to='resto.option')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='resto.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resto_cart', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['region', 'is_approved', 'is_active'], name='resto_restaurant_region_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['category', '-created_at'], name='resto_restaurant_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status', '-created_at'], name='resto_order_resto_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='resto_order_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier', 'status'], name='resto_order_courier_idx'),
        ),
    ]
