# Generated by Django 4.2.25 on 2026-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='removed_ingredients',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text="Un par ligne. Le client pourra les décocher. Mettez « ! » devant ceux qu'on ne peut pas retirer (ex : !Riz).", verbose_name='Ingrédients'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='removed_ingredients',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
