# Generated by Django 4.2.25 on 2026-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_menuitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preparation',
            field=models.TextField(blank=True, default='', help_text='Comment le plat est préparé : cuisson, mode de préparation, temps, particularités.', verbose_name='Préparation'),
        ),
    ]
