# Generated by Django 4.2.25 on 2026-09-05 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resto', '0003_menuitem_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('customer', 'Client'), ('restaurant', 'Restaurant'), ('courier', 'Livreur')], max_length=12, verbose_name="Rôle de l'auteur")),
                ('target_role', models.CharField(choices=[('customer', 'Client'), ('restaurant', 'Restaurant'), ('courier', 'Livreur')], db_index=True, max_length=12, verbose_name='Rôle noté')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Note (1-5)')),
                ('payment_ok', models.BooleanField(blank=True, null=True, verbose_name='Paiement sans problème')),
                ('payment_note', models.CharField(blank=True, default='', max_length=200, verbose_name='Précision sur le paiement')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resto.order', verbose_name='Commande')),
                ('target_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resto.courier')),
                ('target_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resto.restaurant')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resto_reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'author_role', 'target_role')},
            },
        ),
    ]
