# Generated by Django 4.2.25 on 2026-09-05 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resto', '0004_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='admin_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes admin'),
        ),
        migrations.AddField(
            model_name='courier',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Quelques mots sur vous : expérience, ponctualité, ce que les clients peuvent attendre.', verbose_name='Présentation'),
        ),
        migrations.AddField(
            model_name='courier',
            name='cin_back',
            field=models.ImageField(blank=True, null=True, upload_to='resto/cin/%Y/%m/', verbose_name='CIN verso'),
        ),
        migrations.AddField(
            model_name='courier',
            name='cin_front',
            field=models.ImageField(blank=True, null=True, upload_to='resto/cin/%Y/%m/', verbose_name='CIN recto'),
        ),
        migrations.AddField(
            model_name='courier',
            name='cin_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='N° de CIN (12 chiffres)'),
        ),
        migrations.AddField(
            model_name='courier',
            name='cin_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Identité vérifiée par Vazimba'),
        ),
        migrations.AddField(
            model_name='courier',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nom complet (comme sur la CIN)'),
        ),
        migrations.AddField(
            model_name='courier',
            name='guarantor_name',
            field=models.CharField(blank=True, default='', help_text='Une personne de confiance (famille, employeur, fokontany) qui répond de vous.', max_length=120, verbose_name='Nom du garant'),
        ),
        migrations.AddField(
            model_name='courier',
            name='guarantor_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone du garant'),
        ),
        migrations.AddField(
            model_name='courier',
            name='hours',
            field=models.CharField(blank=True, default='', help_text='Ex : Lun–Sam 10h–22h', max_length=120, verbose_name='Disponibilités'),
        ),
        migrations.AddField(
            model_name='courier',
            name='languages',
            field=models.CharField(blank=True, default='Malagasy, Français', max_length=120, verbose_name='Langues parlées'),
        ),
        migrations.AddField(
            model_name='courier',
            name='mm_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Numéro mobile money'),
        ),
        migrations.AddField(
            model_name='courier',
            name='mm_provider',
            field=models.CharField(blank=True, choices=[('', 'Espèces uniquement'), ('mvola', 'MVola'), ('orange', 'Orange Money'), ('airtel', 'Airtel Money')], default='', max_length=10, verbose_name='Mobile money'),
        ),
        migrations.AddField(
            model_name='courier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resto/couriers/%Y/%m/', verbose_name='Photo (visage bien visible)'),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resto/vehicles/%Y/%m/', verbose_name='Photo du véhicule'),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_plate',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Immatriculation'),
        ),
        migrations.AddField(
            model_name='courier',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courier',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Années d'expérience en livraison"),
        ),
        migrations.AddField(
            model_name='courier',
            name='zones',
            field=models.CharField(blank=True, default='', help_text='Ex : Analakely, Isoraka, Ankorondrano, 67 Ha', max_length=250, verbose_name='Quartiers couverts'),
        ),
    ]
