# Generated by Django 4.2.25 on 2026-09-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_courier_trust_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='included_ingredients',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ingredients_extra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='included_ingredients',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
